define([
    'lib/text',
    'lib/lodash.underscore',
    'lib/jquery',
    'lib/angular/angular',
    'lib/angular/angular-mobile',
    'lib/angular/angular-carousel',
    'lib/angular/bootstrap',
    'lib/angular/angular-strap',
    'lib/angular/jquery.gridster',
    'lib/angular/angular-gridster',
    'lib/angular/bootstrap-tagsinput',
    'lib/angular/bootstrap-tagsinput-angular',
    'lib/angular/angular-file-upload',
    'lib/angular/styling',
    'extension/lodash.underscore'
]);